language: node_js
node_js: stable
script: npm run build
notifications:
  email: false
after_script:
  - cd ./dist
  - git init
  - git config user.name "LaoHu47"
  - git config user.email "962271461@qq.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master-build
# E: Build LifeCycle

branches:
  only:
    - master
env:
 global:
   - GH_REF: github.com/LaoHu97/Vue-Access-Control-shop